// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADcfwQifybO6ho4kGJqVNwDnTVTyLQ6OU',
    appId: '1:726510929341:web:dcc4afbcb653e5a9cd3ed4',
    messagingSenderId: '726510929341',
    projectId: 'fir-integration-example-9686d',
    authDomain: 'fir-integration-example-9686d.firebaseapp.com',
    storageBucket: 'fir-integration-example-9686d.appspot.com',
    measurementId: 'G-ZZCDVS3S21',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLAksNr2fQEswTbo7-8w62fOUx6BNzKjY',
    appId: '1:726510929341:android:5aaf2fae5fd85756cd3ed4',
    messagingSenderId: '726510929341',
    projectId: 'fir-integration-example-9686d',
    storageBucket: 'fir-integration-example-9686d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChGl0LKLdJ2OhGP3Xu2pTvOHIhzulpyz4',
    appId: '1:726510929341:ios:8546c2c002d6a819cd3ed4',
    messagingSenderId: '726510929341',
    projectId: 'fir-integration-example-9686d',
    storageBucket: 'fir-integration-example-9686d.appspot.com',
    iosClientId: '726510929341-24auv8ekvk0pp0l5bndb0f5pj0pr6tnk.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseIntegrationAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChGl0LKLdJ2OhGP3Xu2pTvOHIhzulpyz4',
    appId: '1:726510929341:ios:8546c2c002d6a819cd3ed4',
    messagingSenderId: '726510929341',
    projectId: 'fir-integration-example-9686d',
    storageBucket: 'fir-integration-example-9686d.appspot.com',
    iosClientId: '726510929341-24auv8ekvk0pp0l5bndb0f5pj0pr6tnk.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseIntegrationAuth',
  );
}
